import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage debe usarse dentro de LanguageProvider');
  }
  return context;
};

const translations = {
  es: {
    // Autenticación
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    username: 'Usuario',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    email: 'Correo Electrónico',
    firstName: 'Nombre',
    lastName: 'Apellido',
    rememberMe: 'Recordarme',
    forgotPassword: '¿Olvidaste tu contraseña?',
    dontHaveAccount: '¿No tienes una cuenta?',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    
    // Navegación
    dashboard: 'Panel de Control',
    clients: 'Clientes',
    products: 'Productos',
    sales: 'Ventas',
    purchases: 'Compras',
    quotes: 'Presupuestos',
    cashRegister: 'Caja',
    reports: 'Reportes',
    settings: 'Configuración',
    users: 'Usuarios',
    branches: 'Sucursales',
    
    // Común
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Agregar',
    search: 'Buscar',
    filter: 'Filtrar',
    actions: 'Acciones',
    loading: 'Cargando...',
    noData: 'No hay datos disponibles',
    confirm: 'Confirmar',
    back: 'Volver',
    next: 'Siguiente',
    finish: 'Finalizar',
    
    // Mensajes
    success: 'Éxito',
    error: 'Error',
    warning: 'Advertencia',
    info: 'Información',
    loginSuccess: 'Inicio de sesión exitoso',
    loginError: 'Error al iniciar sesión',
    registerSuccess: 'Registro exitoso',
    registerError: 'Error al registrar usuario',
    
    // Clientes
    clientType: 'Tipo de Cliente',
    retail: 'Minorista',
    wholesale: 'Mayorista',
    construction: 'Obra',
    businessName: 'Razón Social',
    tradeName: 'Nombre Comercial',
    taxId: 'CUIT/DNI',
    phone: 'Teléfono',
    address: 'Dirección',
    city: 'Localidad',
    province: 'Provincia',
    postalCode: 'Código Postal',
    creditLimit: 'Límite de Crédito',
    paymentTerms: 'Condiciones de Pago',
    
    // Productos
    productCode: 'Código',
    description: 'Descripción',
    category: 'Categoría',
    brand: 'Marca',
    unitOfMeasure: 'Unidad de Medida',
    stock: 'Stock',
    minStock: 'Stock Mínimo',
    price: 'Precio',
    priceList: 'Lista de Precios',
    product: 'Producto',
    newProduct: 'Nuevo Producto',
    editProduct: 'Editar Producto',
    productDetails: 'Detalle de Producto',
    productsList: 'Lista de Productos',
    stockCurrent: 'Stock Actual',
    stockMinimum: 'Stock Mínimo',
    location: 'Ubicación',
    provider: 'Proveedor',
    image: 'Imagen',
    prices: 'Precios',
    updatePrices: 'Actualizar Precios',
    pricesByList: 'Precios por Lista',
    lowStockAlert: 'Stock Bajo',
    outOfStock: 'Sin Stock',
    categories: 'Categorías',
    newCategory: 'Nueva Categoría',
    parentCategory: 'Categoría Padre',
    subcategories: 'Subcategorías',
    
    // Ventas
    saleNumber: 'Número de Venta',
    date: 'Fecha',
    client: 'Cliente',
    total: 'Total',
    subtotal: 'Subtotal',
    discount: 'Descuento',
    taxes: 'Impuestos',
    paymentMethod: 'Forma de Pago',
    cash: 'Efectivo',
    transfer: 'Transferencia',
    check: 'Cheque',
    creditAccount: 'Cuenta Corriente',
    sale: 'Venta',
    newSale: 'Nueva Venta',
    saleDetails: 'Detalle de Venta',
    invoice: 'Factura',
    receipt: 'Ticket',
    invoiceA: 'Factura A',
    invoiceB: 'Factura B',
    invoiceC: 'Factura C',
    deliveryNote: 'Remito',
    voucherType: 'Tipo de Comprobante',
    card: 'Tarjeta',
    currentAccount: 'Cuenta Corriente',
    completed: 'Completada',
    cancelled: 'Anulada',
    cancelSale: 'Anular Venta',
    fromQuote: 'Desde Presupuesto',

    // Compras
    purchase: 'Compra',
    newPurchase: 'Nueva Compra',
    purchaseDetails: 'Detalle de Compra',
    purchaseNumber: 'Número de Compra',
    supplierInvoice: 'Factura del Proveedor',
    invoiceNumber: 'Número de Factura',
    received: 'Recibida',
    paid: 'Pagada',
    cancelPurchase: 'Anular Compra',
    costPrice: 'Precio de Costo',

    // Dashboard
    totalSales: 'Ventas Totales',
    totalClients: 'Clientes Totales',
    lowStock: 'Productos con Stock Bajo',
    pendingQuotes: 'Presupuestos Pendientes',
    todaySales: 'Ventas de Hoy',
    monthlySales: 'Ventas del Mes',
    topProducts: 'Productos Más Vendidos',
    topClients: 'Mejores Clientes',
    
    // App
    appName: 'DS-Corralón',
    appDescription: 'Sistema de Gestión para Corralones',
    welcome: 'Bienvenido',
    selectLanguage: 'Seleccionar Idioma',

    // Proveedores
    providers: 'Proveedores',
    newProvider: 'Nuevo Proveedor',
    editProvider: 'Editar Proveedor',
    providerDetails: 'Detalle de Proveedor',
    providersList: 'Lista de Proveedores',
    website: 'Sitio Web',
    associatedProducts: 'Productos Asociados',

    // Presupuestos
    quote: 'Presupuesto',
    newQuote: 'Nuevo Presupuesto',
    editQuote: 'Editar Presupuesto',
    quoteDetails: 'Detalle de Presupuesto',
    quoteNumber: 'Número',
    expirationDate: 'Fecha de Vencimiento',
    validUntil: 'Válido hasta',
    pending: 'Pendiente',
    approved: 'Aprobado',
    rejected: 'Rechazado',
    converted: 'Convertido',
    addProduct: 'Agregar Producto',
    selectProduct: 'Seleccionar producto',
    quantity: 'Cantidad',
    unitPrice: 'Precio Unitario',
    discountPercentage: 'Descuento %',
    discountAmount: 'Descuento Monto',

    // Cuenta Corriente
    accountStatement: 'Estado de Cuenta',
    registerPayment: 'Registrar Pago',
    payment: 'Pago',
    payments: 'Pagos',
    debt: 'Deuda',
    balance: 'Saldo',
    availableCredit: 'Crédito Disponible',
    overLimit: 'Sobre Límite',
    debit: 'Débito',
    credit: 'Crédito',
    receiptNumber: 'Número de Comprobante',
    dueDate: 'Fecha de Vencimiento',
    previousBalance: 'Saldo Anterior',
    newBalance: 'Saldo Nuevo',
    totalDebt: 'Deuda Total',
    clientsWithDebt: 'Clientes con Deuda',
    topDebtors: 'Mayores Deudores',
    recentMovements: 'Movimientos Recientes',

    // Caja
    openCashRegister: 'Abrir Caja',
    closeCashRegister: 'Cerrar Caja',
    cashMovement: 'Movimiento de Caja',
    openedCash: 'Caja Abierta',
    closedCash: 'Caja Cerrada',
    initialAmount: 'Monto Inicial',
    finalAmount: 'Monto Final',
    currentAmount: 'Monto Actual',
    expectedAmount: 'Monto Esperado',
    difference: 'Diferencia',
    income: 'Ingreso',
    expense: 'Egreso',
    totalIncome: 'Total Ingresos',
    totalExpenses: 'Total Egresos',
    cashMovements: 'Movimientos de Caja',
    registerMovement: 'Registrar Movimiento',
    movementType: 'Tipo de Movimiento',
    concept: 'Concepto',
    openingNotes: 'Observaciones de Apertura',
    closingNotes: 'Observaciones de Cierre',
    cashNumber: 'Caja N°',
    openedBy: 'Abierta por',
    closedBy: 'Cerrada por',
    openingDate: 'Fecha de Apertura',
    closingDate: 'Fecha de Cierre',

    // Dashboard y Reportes
    salesReport: 'Reporte de Ventas',
    productsReport: 'Reporte de Productos',
    clientsReport: 'Reporte de Clientes',
    stockReport: 'Reporte de Stock',
    cashReport: 'Reporte de Caja',
    profitabilityReport: 'Reporte de Rentabilidad',
    monthSales: 'Ventas del Mes',
    criticalStock: 'Stock Crítico',
    openCash: 'Cajas Abiertas',
    pendingBudgets: 'Presupuestos Pendientes',
    salesLast7Days: 'Ventas Últimos 7 Días',
    viewReport: 'Ver Reporte',
    period: 'Período',
    from: 'Desde',
    to: 'Hasta',
    groupBy: 'Agrupar por',
    day: 'Día',
    month: 'Mes',
    year: 'Año',
    averageTicket: 'Ticket Promedio',
    byPaymentMethod: 'Por Forma de Pago',
    bestSellingProducts: 'Productos Más Vendidos',
    unitsSold: 'Unidades Vendidas',
    lastPurchase: 'Última Compra',
    stockStatus: 'Estado del Stock',
    normalStock: 'Stock Normal',
    profitability: 'Rentabilidad',
    margin: 'Margen',
    profit: 'Ganancia',

    // Sucursales
    branch: 'Sucursal',
    newBranch: 'Nueva Sucursal',
    editBranch: 'Editar Sucursal',
    branchCode: 'Código',
    branchName: 'Nombre',
    manager: 'Responsable',
    active: 'Activa',
    inactive: 'Inactiva',
    activeBranches: 'Sucursales Activas',

    // Usuarios
    user: 'Usuario',
    newUser: 'Nuevo Usuario',
    editUser: 'Editar Usuario',
    role: 'Rol',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    changePassword: 'Cambiar Contraseña',
    admin: 'Administrador',
    seller: 'Vendedor',
    cashier: 'Cajero',
    activeUsers: 'Usuarios Activos',
    inactiveUsers: 'Usuarios Inactivos',
    assignedBranch: 'Sucursal Asignada',
    noBranch: 'Sin sucursal',
  },
  
  en: {
    // Authentication
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    email: 'Email',
    firstName: 'First Name',
    lastName: 'Last Name',
    rememberMe: 'Remember Me',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    
    // Navigation
    dashboard: 'Dashboard',
    clients: 'Clients',
    products: 'Products',
    sales: 'Sales',
    purchases: 'Purchases',
    quotes: 'Quotes',
    cashRegister: 'Cash Register',
    reports: 'Reports',
    settings: 'Settings',
    users: 'Users',
    branches: 'Branches',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    actions: 'Actions',
    loading: 'Loading...',
    noData: 'No data available',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    finish: 'Finish',
    
    // Messages
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Information',
    loginSuccess: 'Login successful',
    loginError: 'Login error',
    registerSuccess: 'Registration successful',
    registerError: 'Registration error',
    
    // Clients
    clientType: 'Client Type',
    retail: 'Retail',
    wholesale: 'Wholesale',
    construction: 'Construction',
    businessName: 'Business Name',
    tradeName: 'Trade Name',
    taxId: 'Tax ID',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    province: 'Province',
    postalCode: 'Postal Code',
    creditLimit: 'Credit Limit',
    paymentTerms: 'Payment Terms',
    
    // Products
    productCode: 'Code',
    description: 'Description',
    category: 'Category',
    brand: 'Brand',
    unitOfMeasure: 'Unit of Measure',
    stock: 'Stock',
    minStock: 'Min Stock',
    price: 'Price',
    priceList: 'Price List',
    product: 'Product',
    newProduct: 'New Product',
    editProduct: 'Edit Product',
    productDetails: 'Product Details',
    productsList: 'Products List',
    stockCurrent: 'Current Stock',
    stockMinimum: 'Minimum Stock',
    location: 'Location',
    provider: 'Provider',
    image: 'Image',
    prices: 'Prices',
    updatePrices: 'Update Prices',
    pricesByList: 'Prices by List',
    lowStockAlert: 'Low Stock',
    outOfStock: 'Out of Stock',
    categories: 'Categories',
    newCategory: 'New Category',
    parentCategory: 'Parent Category',
    subcategories: 'Subcategories',
    
    // Sales
    saleNumber: 'Sale Number',
    date: 'Date',
    client: 'Client',
    total: 'Total',
    subtotal: 'Subtotal',
    discount: 'Discount',
    taxes: 'Taxes',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    transfer: 'Transfer',
    check: 'Check',
    creditAccount: 'Credit Account',
    sale: 'Sale',
    newSale: 'New Sale',
    saleDetails: 'Sale Details',
    invoice: 'Invoice',
    receipt: 'Receipt',
    invoiceA: 'Invoice A',
    invoiceB: 'Invoice B',
    invoiceC: 'Invoice C',
    deliveryNote: 'Delivery Note',
    voucherType: 'Voucher Type',
    card: 'Card',
    currentAccount: 'Current Account',
    completed: 'Completed',
    cancelled: 'Cancelled',
    cancelSale: 'Cancel Sale',
    fromQuote: 'From Quote',

    // Purchases
    purchase: 'Purchase',
    newPurchase: 'New Purchase',
    purchaseDetails: 'Purchase Details',
    purchaseNumber: 'Purchase Number',
    supplierInvoice: 'Supplier Invoice',
    invoiceNumber: 'Invoice Number',
    received: 'Received',
    paid: 'Paid',
    cancelPurchase: 'Cancel Purchase',
    costPrice: 'Cost Price',

    // Dashboard
    totalSales: 'Total Sales',
    totalClients: 'Total Clients',
    lowStock: 'Low Stock Products',
    pendingQuotes: 'Pending Quotes',
    todaySales: "Today's Sales",
    monthlySales: 'Monthly Sales',
    topProducts: 'Top Products',
    topClients: 'Top Clients',
    
    // App
    appName: 'DS-Hardware Store',
    appDescription: 'Hardware Store Management System',
    welcome: 'Welcome',
    selectLanguage: 'Select Language',

    // Providers
    providers: 'Providers',
    newProvider: 'New Provider',
    editProvider: 'Edit Provider',
    providerDetails: 'Provider Details',
    providersList: 'Providers List',
    website: 'Website',
    associatedProducts: 'Associated Products',

    // Quotes
    quote: 'Quote',
    newQuote: 'New Quote',
    editQuote: 'Edit Quote',
    quoteDetails: 'Quote Details',
    quoteNumber: 'Number',
    expirationDate: 'Expiration Date',
    validUntil: 'Valid until',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    converted: 'Converted',
    addProduct: 'Add Product',
    selectProduct: 'Select product',
    quantity: 'Quantity',
    unitPrice: 'Unit Price',
    discountPercentage: 'Discount %',
    discountAmount: 'Discount Amount',

    // Current Account
    accountStatement: 'Account Statement',
    registerPayment: 'Register Payment',
    payment: 'Payment',
    payments: 'Payments',
    debt: 'Debt',
    balance: 'Balance',
    availableCredit: 'Available Credit',
    overLimit: 'Over Limit',
    debit: 'Debit',
    credit: 'Credit',
    receiptNumber: 'Receipt Number',
    dueDate: 'Due Date',
    previousBalance: 'Previous Balance',
    newBalance: 'New Balance',
    totalDebt: 'Total Debt',
    clientsWithDebt: 'Clients with Debt',
    topDebtors: 'Top Debtors',
    recentMovements: 'Recent Movements',

    // Cash Register
    openCashRegister: 'Open Cash Register',
    closeCashRegister: 'Close Cash Register',
    cashMovement: 'Cash Movement',
    openedCash: 'Opened Cash',
    closedCash: 'Closed Cash',
    initialAmount: 'Initial Amount',
    finalAmount: 'Final Amount',
    currentAmount: 'Current Amount',
    expectedAmount: 'Expected Amount',
    difference: 'Difference',
    income: 'Income',
    expense: 'Expense',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    cashMovements: 'Cash Movements',
    registerMovement: 'Register Movement',
    movementType: 'Movement Type',
    concept: 'Concept',
    openingNotes: 'Opening Notes',
    closingNotes: 'Closing Notes',
    cashNumber: 'Cash N°',
    openedBy: 'Opened by',
    closedBy: 'Closed by',
    openingDate: 'Opening Date',
    closingDate: 'Closing Date',

    // Dashboard and Reports
    salesReport: 'Sales Report',
    productsReport: 'Products Report',
    clientsReport: 'Clients Report',
    stockReport: 'Stock Report',
    cashReport: 'Cash Report',
    profitabilityReport: 'Profitability Report',
    monthSales: "Month's Sales",
    criticalStock: 'Critical Stock',
    openCash: 'Open Cash',
    pendingBudgets: 'Pending Budgets',
    salesLast7Days: 'Sales Last 7 Days',
    viewReport: 'View Report',
    period: 'Period',
    from: 'From',
    to: 'To',
    groupBy: 'Group by',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    averageTicket: 'Average Ticket',
    byPaymentMethod: 'By Payment Method',
    bestSellingProducts: 'Best Selling Products',
    unitsSold: 'Units Sold',
    lastPurchase: 'Last Purchase',
    stockStatus: 'Stock Status',
    normalStock: 'Normal Stock',
    profitability: 'Profitability',
    margin: 'Margin',
    profit: 'Profit',

    // Branches
    branch: 'Branch',
    newBranch: 'New Branch',
    editBranch: 'Edit Branch',
    branchCode: 'Code',
    branchName: 'Name',
    manager: 'Manager',
    active: 'Active',
    inactive: 'Inactive',
    activeBranches: 'Active Branches',

    // Users
    user: 'User',
    newUser: 'New User',
    editUser: 'Edit User',
    role: 'Role',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    changePassword: 'Change Password',
    admin: 'Administrator',
    seller: 'Seller',
    cashier: 'Cashier',
    activeUsers: 'Active Users',
    inactiveUsers: 'Inactive Users',
    assignedBranch: 'Assigned Branch',
    noBranch: 'No branch',
  },
  
  pt: {
    // Autenticação
    login: 'Entrar',
    register: 'Registrar',
    logout: 'Sair',
    username: 'Usuário',
    password: 'Senha',
    confirmPassword: 'Confirmar Senha',
    email: 'E-mail',
    firstName: 'Nome',
    lastName: 'Sobrenome',
    rememberMe: 'Lembrar-me',
    forgotPassword: 'Esqueceu a senha?',
    dontHaveAccount: 'Não tem uma conta?',
    alreadyHaveAccount: 'Já tem uma conta?',
    
    // Navegação
    dashboard: 'Painel de Controle',
    clients: 'Clientes',
    products: 'Produtos',
    sales: 'Vendas',
    purchases: 'Compras',
    quotes: 'Orçamentos',
    cashRegister: 'Caixa',
    reports: 'Relatórios',
    settings: 'Configurações',
    users: 'Usuários',
    branches: 'Filiais',
    
    // Comum
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    add: 'Adicionar',
    search: 'Pesquisar',
    filter: 'Filtrar',
    actions: 'Ações',
    loading: 'Carregando...',
    noData: 'Nenhum dado disponível',
    confirm: 'Confirmar',
    back: 'Voltar',
    next: 'Próximo',
    finish: 'Finalizar',
    
    // Mensagens
    success: 'Sucesso',
    error: 'Erro',
    warning: 'Aviso',
    info: 'Informação',
    loginSuccess: 'Login bem-sucedido',
    loginError: 'Erro ao fazer login',
    registerSuccess: 'Registro bem-sucedido',
    registerError: 'Erro ao registrar usuário',
    
    // Clientes
    clientType: 'Tipo de Cliente',
    retail: 'Varejo',
    wholesale: 'Atacado',
    construction: 'Obra',
    businessName: 'Razão Social',
    tradeName: 'Nome Comercial',
    taxId: 'CPF/CNPJ',
    phone: 'Telefone',
    address: 'Endereço',
    city: 'Cidade',
    province: 'Estado',
    postalCode: 'CEP',
    creditLimit: 'Limite de Crédito',
    paymentTerms: 'Condições de Pagamento',
    
    // Produtos
    productCode: 'Código',
    description: 'Descrição',
    category: 'Categoria',
    brand: 'Marca',
    unitOfMeasure: 'Unidade de Medida',
    stock: 'Estoque',
    minStock: 'Estoque Mínimo',
    price: 'Preço',
    priceList: 'Lista de Preços',
    product: 'Produto',
    newProduct: 'Novo Produto',
    editProduct: 'Editar Produto',
    productDetails: 'Detalhes do Produto',
    productsList: 'Lista de Produtos',
    stockCurrent: 'Estoque Atual',
    stockMinimum: 'Estoque Mínimo',
    location: 'Localização',
    provider: 'Fornecedor',
    image: 'Imagem',
    prices: 'Preços',
    updatePrices: 'Atualizar Preços',
    pricesByList: 'Preços por Lista',
    lowStockAlert: 'Estoque Baixo',
    outOfStock: 'Sem Estoque',
    categories: 'Categorias',
    newCategory: 'Nova Categoria',
    parentCategory: 'Categoria Pai',
    subcategories: 'Subcategorias',
    
    // Vendas
    saleNumber: 'Número da Venda',
    date: 'Data',
    client: 'Cliente',
    total: 'Total',
    subtotal: 'Subtotal',
    discount: 'Desconto',
    taxes: 'Impostos',
    paymentMethod: 'Forma de Pagamento',
    cash: 'Dinheiro',
    transfer: 'Transferência',
    check: 'Cheque',
    creditAccount: 'Conta Corrente',
    sale: 'Venda',
    newSale: 'Nova Venda',
    saleDetails: 'Detalhes da Venda',
    invoice: 'Fatura',
    receipt: 'Recibo',
    invoiceA: 'Fatura A',
    invoiceB: 'Fatura B',
    invoiceC: 'Fatura C',
    deliveryNote: 'Nota de Entrega',
    voucherType: 'Tipo de Comprovante',
    card: 'Cartão',
    currentAccount: 'Conta Corrente',
    completed: 'Concluída',
    cancelled: 'Cancelada',
    cancelSale: 'Cancelar Venda',
    fromQuote: 'Do Orçamento',

    // Compras..
    purchase: 'Compra',
    newPurchase: 'Nova Compra',
    purchaseDetails: 'Detalhes da Compra',
    purchaseNumber: 'Número da Compra',
    supplierInvoice: 'Fatura do Fornecedor',
    invoiceNumber: 'Número da Fatura',
    received: 'Recebida',
    paid: 'Paga',
    cancelPurchase: 'Cancelar Compra',
    costPrice: 'Preço de Custo',

    // Dashboard
    totalSales: 'Vendas Totais',
    totalClients: 'Clientes Totais',
    lowStock: 'Produtos com Estoque Baixo',
    pendingQuotes: 'Orçamentos Pendentes',
    todaySales: 'Vendas de Hoje',
    monthlySales: 'Vendas do Mês',
    topProducts: 'Produtos Mais Vendidos',
    topClients: 'Melhores Clientes',
    
    // App
    appName: 'DS-Depósito',
    appDescription: 'Sistema de Gestão para Depósitos',
    welcome: 'Bem-vindo',
    selectLanguage: 'Selecionar Idioma',

    // Fornecedores
    providers: 'Fornecedores',
    newProvider: 'Novo Fornecedor',
    editProvider: 'Editar Fornecedor',
    providerDetails: 'Detalhes do Fornecedor',
    providersList: 'Lista de Fornecedores',
    website: 'Site',
    associatedProducts: 'Produtos Associados',

    // Orçamentos
    quote: 'Orçamento',
    newQuote: 'Novo Orçamento',
    editQuote: 'Editar Orçamento',
    quoteDetails: 'Detalhes do Orçamento',
    quoteNumber: 'Número',
    expirationDate: 'Data de Vencimento',
    validUntil: 'Válido até',
    pending: 'Pendente',
    approved: 'Aprovado',
    rejected: 'Rejeitado',
    converted: 'Convertido',
    addProduct: 'Adicionar Produto',
    selectProduct: 'Selecionar produto',
    quantity: 'Quantidade',
    unitPrice: 'Preço Unitário',
    discountPercentage: 'Desconto %',
    discountAmount: 'Valor do Desconto',

    // Conta Corrente
    accountStatement: 'Extrato de Conta',
    registerPayment: 'Registrar Pagamento',
    payment: 'Pagamento',
    payments: 'Pagamentos',
    debt: 'Dívida',
    balance: 'Saldo',
    availableCredit: 'Crédito Disponível',
    overLimit: 'Acima do Limite',
    debit: 'Débito',
    credit: 'Crédito',
    receiptNumber: 'Número do Comprovante',
    dueDate: 'Data de Vencimento',
    previousBalance: 'Saldo Anterior',
    newBalance: 'Saldo Novo',
    totalDebt: 'Dívida Total',
    clientsWithDebt: 'Clientes com Dívida',
    topDebtors: 'Maiores Devedores',
    recentMovements: 'Movimentos Recentes',

    // Caixa
    openCashRegister: 'Abrir Caixa',
    closeCashRegister: 'Fechar Caixa',
    cashMovement: 'Movimento de Caixa',
    openedCash: 'Caixa Aberta',
    closedCash: 'Caixa Fechada',
    initialAmount: 'Valor Inicial',
    finalAmount: 'Valor Final',
    currentAmount: 'Valor Atual',
    expectedAmount: 'Valor Esperado',
    difference: 'Diferença',
    income: 'Entrada',
    expense: 'Saída',
    totalIncome: 'Total Entradas',
    totalExpenses: 'Total Saídas',
    cashMovements: 'Movimentos de Caixa',
    registerMovement: 'Registrar Movimento',
    movementType: 'Tipo de Movimento',
    concept: 'Conceito',
    openingNotes: 'Observações de Abertura',
    closingNotes: 'Observações de Fechamento',
    cashNumber: 'Caixa N°',
    openedBy: 'Aberta por',
    closedBy: 'Fechada por',
    openingDate: 'Data de Abertura',
    closingDate: 'Data de Fechamento',

    // Dashboard e Relatórios
    salesReport: 'Relatório de Vendas',
    productsReport: 'Relatório de Produtos',
    clientsReport: 'Relatório de Clientes',
    stockReport: 'Relatório de Estoque',
    cashReport: 'Relatório de Caixa',
    profitabilityReport: 'Relatório de Rentabilidade',
    monthSales: 'Vendas do Mês',
    criticalStock: 'Estoque Crítico',
    openCash: 'Caixas Abertas',
    pendingBudgets: 'Orçamentos Pendentes',
    salesLast7Days: 'Vendas Últimos 7 Dias',
    viewReport: 'Ver Relatório',
    period: 'Período',
    from: 'De',
    to: 'Até',
    groupBy: 'Agrupar por',
    day: 'Dia',
    month: 'Mês',
    year: 'Ano',
    averageTicket: 'Ticket Médio',
    byPaymentMethod: 'Por Forma de Pagamento',
    bestSellingProducts: 'Produtos Mais Vendidos',
    unitsSold: 'Unidades Vendidas',
    lastPurchase: 'Última Compra',
    stockStatus: 'Estado do Estoque',
    normalStock: 'Estoque Normal',
    profitability: 'Rentabilidade',
    margin: 'Margem',
    profit: 'Lucro',

    // Filiais
    branch: 'Filial',
    newBranch: 'Nova Filial',
    editBranch: 'Editar Filial',
    branchCode: 'Código',
    branchName: 'Nome',
    manager: 'Responsável',
    active: 'Ativa',
    inactive: 'Inativa',
    activeBranches: 'Filiais Ativas',

    // Usuários
    user: 'Usuário',
    newUser: 'Novo Usuário',
    editUser: 'Editar Usuário',
    role: 'Função',
    currentPassword: 'Senha Atual',
    newPassword: 'Nova Senha',
    changePassword: 'Alterar Senha',
    admin: 'Administrador',
    seller: 'Vendedor',
    cashier: 'Caixa',
    activeUsers: 'Usuários Ativos',
    inactiveUsers: 'Usuários Inativos',
    assignedBranch: 'Filial Atribuída',
    noBranch: 'Sem filial',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};