export const countries = [
  { code: 'AR', name: 'Argentina' },
  { code: 'BR', name: 'Brasil' },
  { code: 'CL', name: 'Chile' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'PE', name: 'Perú' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'CO', name: 'Colombia' },
  { code: 'VE', name: 'Venezuela' },
];

export const provinces = {
  AR: [
    'Buenos Aires',
    'Catamarca',
    'Chaco',
    'Chubut',
    'Córdoba',
    'Corrientes',
    'Entre Ríos',
    'Formosa',
    'Jujuy',
    'La Pampa',
    'La Rioja',
    'Mendoza',
    'Misiones',
    'Neuquén',
    'Río Negro',
    'Salta',
    'San Juan',
    'San Luis',
    'Santa Cruz',
    'Santa Fe',
    'Santiago del Estero',
    'Tierra del Fuego',
    'Tucumán',
  ],
  BR: [
    'Acre',
    'Alagoas',
    'Amapá',
    'Amazonas',
    'Bahia',
    'Ceará',
    'Distrito Federal',
    'Espírito Santo',
    'Goiás',
    'Maranhão',
    'Mato Grosso',
    'Mato Grosso do Sul',
    'Minas Gerais',
    'Pará',
    'Paraíba',
    'Paraná',
    'Pernambuco',
    'Piauí',
    'Rio de Janeiro',
    'Rio Grande do Norte',
    'Rio Grande do Sul',
    'Rondônia',
    'Roraima',
    'Santa Catarina',
    'São Paulo',
    'Sergipe',
    'Tocantins',
  ],
  CL: [
    'Región Metropolitana',
    'Valparaíso',
    'Biobío',
    'Maule',
    'La Araucanía',
    'Los Lagos',
    'O\'Higgins',
    'Coquimbo',
    'Antofagasta',
    'Los Ríos',
    'Aysén',
    'Tarapacá',
    'Arica y Parinacota',
    'Atacama',
    'Magallanes',
  ],
  UY: [
    'Montevideo',
    'Canelones',
    'Maldonado',
    'Colonia',
    'Rocha',
    'Salto',
    'Paysandú',
    'Rivera',
    'Soriano',
    'Tacuarembó',
  ],
  PY: [
    'Asunción',
    'Central',
    'Alto Paraná',
    'Itapúa',
    'Cordillera',
    'Caaguazú',
    'Amambay',
    'Paraguarí',
  ],
};

export const cities = {
  'Buenos Aires': [
    'La Plata',
    'Mar del Plata',
    'Bahía Blanca',
    'Tandil',
    'San Nicolás',
    'Pergamino',
    'Zárate',
    'Campana',
    'Luján',
    'Mercedes',
    'Olavarría',
    'Junín',
    'Necochea',
    'Chivilcoy',
    'Azul',
  ],
  'Córdoba': [
    'Córdoba Capital',
    'Villa María',
    'Río Cuarto',
    'San Francisco',
    'Villa Carlos Paz',
    'Alta Gracia',
    'Bell Ville',
  ],
  'Santa Fe': [
    'Santa Fe Capital',
    'Rosario',
    'Rafaela',
    'Venado Tuerto',
    'Reconquista',
    'Esperanza',
  ],
  'Mendoza': [
    'Mendoza Capital',
    'San Rafael',
    'Godoy Cruz',
    'Guaymallén',
    'Luján de Cuyo',
  ],
  'Tucumán': [
    'San Miguel de Tucumán',
    'Yerba Buena',
    'Tafí Viejo',
    'Banda del Río Salí',
  ],
  'Salta': [
    'Salta Capital',
    'San Ramón de la Nueva Orán',
    'Tartagal',
    'Metán',
  ],
  'Entre Ríos': [
    'Paraná',
    'Concordia',
    'Gualeguaychú',
    'Concepción del Uruguay',
  ],
  'Misiones': [
    'Posadas',
    'Oberá',
    'Eldorado',
    'Puerto Iguazú',
  ],
  'Chaco': [
    'Resistencia',
    'Presidencia Roque Sáenz Peña',
    'Villa Ángela',
  ],
  'Corrientes': [
    'Corrientes Capital',
    'Goya',
    'Curuzú Cuatiá',
    'Paso de los Libres',
  ],
  'Santiago del Estero': [
    'Santiago del Estero Capital',
    'La Banda',
    'Termas de Río Hondo',
  ],
  'San Juan': [
    'San Juan Capital',
    'Pocito',
    'Rawson',
  ],
  'Jujuy': [
    'San Salvador de Jujuy',
    'Palpalá',
    'Libertador General San Martín',
  ],
  'Río Negro': [
    'Viedma',
    'San Carlos de Bariloche',
    'Cipolletti',
    'General Roca',
  ],
  'Neuquén': [
    'Neuquén Capital',
    'Cutral-Có',
    'Zapala',
    'San Martín de los Andes',
  ],
  'Chubut': [
    'Rawson',
    'Comodoro Rivadavia',
    'Puerto Madryn',
    'Trelew',
  ],
  'Santa Cruz': [
    'Río Gallegos',
    'Caleta Olivia',
    'Pico Truncado',
  ],
  'Tierra del Fuego': [
    'Ushuaia',
    'Río Grande',
    'Tolhuin',
  ],
  'Formosa': [
    'Formosa Capital',
    'Clorinda',
    'Pirané',
  ],
  'La Rioja': [
    'La Rioja Capital',
    'Chilecito',
    'Aimogasta',
  ],
  'Catamarca': [
    'San Fernando del Valle de Catamarca',
    'Belén',
    'Andalgalá',
  ],
  'San Luis': [
    'San Luis Capital',
    'Villa Mercedes',
    'Merlo',
  ],
  'La Pampa': [
    'Santa Rosa',
    'General Pico',
    'Toay',
  ],
};

export const getProvincesByCountry = (countryCode) => {
  return provinces[countryCode] || [];
};

export const getCitiesByProvince = (provinceName) => {
  return cities[provinceName] || [];
};